### ISSUE TITLE
gh handles of the remaining group members

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/raw-image-data-previewer#1]
Hi @MaciejFranikowski and @Ty7ak 

Please tell the remaining group members to adjust their github handles so that we can easily identify everyone (the current ones are not acceptable).

If they do not wish to change their github names, they can create new accounts.

**Comment by Ty7ak** [comment]
Hey, sorry for the inconvenience.

The handles have been changed accordingly:
blazejulanowicz
DopartDawid

**Comment by tgorochowik** [comment]
Thanks
