### ISSUE TITLE
Create spreadsheet with supported color formats

### ISSUE THREAD

**Issue by blazejulanowicz** [antmicro-labs/raw-image-data-previewer#17]
We need to define, which color formats are supported by our utility. It will be useful for development purposes but mainly it will be an addition to documentation:

Structured color formats (color components ARE IN ONE BLOCK i. e. rrrbbbggg):
- these are easy to implement and parsing is quite universal
- a definition which pixel planes are supported
- a definition which pixel formats (ARGB, RGBA, BGR etc.) are supported
- user will be able to define their own

Unstructured color formats (color components are spread around pixel i. e. rbbbgggrr):
- are they supported at all?
- if yes, which ones are supported (parsing utility won't be universal so we must declare which ones will be available)
- user won't be able to define their own unstructured color format

[YUV](https://wiki.videolan.org/YUV) color formats:
- for now only packed (so we must implement at least UYVY and YUY2)
- we need to remember that they are packed differently than RGB-like
- user should be able to define their own (bits per component, endiannes etc.)

It needs to be consulted with company members, which formats should we focus on.

**Comment by tgorochowik** [comment]
> Unstructured color formats (color components are spread around pixel i. e. rbbbgggrr):
> 
> * are they supported at all?
> * if yes, which ones are supported (parsing utility won't be universal so we must declare which ones will be available)
> * user won't be able to define their own unstructured color format

Could you give an example where did you find references to such formats?

As for priorities, I would say:
* RGB24
* RGB32
* YUV 4:2:2
* YUV 4:2:0
* BAYER (RGGB, RGBG, GRGB etc - is that what you meant by "unstructured"? These formats are actually quite common when dealing with raw data from sensors, they also have various sizes)
* Planar YUVs

You of course shouldn't have to implement all of them at the very start, defining just a few formats should allow you work on the other parts of the application and then the work on the remaining formats can be parallelized.

**Comment by blazejulanowicz** [comment]
[liunxtv.org color formats definitions](https://linuxtv.org/downloads/v4l-dvb-apis/userspace-api/v4l/pixfmt-rgb.html) - you can find "unstructured" or "mixed" color format under i. e. `V4L2_PIX_FMT_RGB565`.

----

> As for priorities, I would say:
> 
>     * RGB24
> 
>     * RGB32
> 
>     * YUV 4:2:2
> 
>     * YUV 4:2:0
> 
>     * BAYER (RGGB, RGBG, GRGB etc - is that what you meant by "unstructured"? These formats are actually quite common when dealing with raw data from sensors, they also have various sizes)
> 
>     * Planar YUVs

Thanks, we will focus on those ones.

**Comment by tgorochowik** [comment]
> [liunxtv.org color formats definitions](https://linuxtv.org/downloads/v4l-dvb-apis/userspace-api/v4l/pixfmt-rgb.html) - you can find "unstructured" or "mixed" color format under i. e. `V4L2_PIX_FMT_RGB565`.

I don't see any occurrences or "unstructured" or "mixed" there? RGB565 is a regular 16 bit format.
And now that you mention it - it would be nice to have those shorter formats too!

And of course I completely forgot about gray formats on my list. We definitely need gray formats of various widths (8bit grey being the minimum - but I guess this should be fairly easy to add).

**Comment by blazejulanowicz** [comment]
Okay, we will also include grays and Bayer formats in our spreadsheet.

About this unstructured formats, I needed to read those bytes like computer not like human. Now I see they are normal ones x)
Thanks!

**Comment by blazejulanowicz** [comment]
@tgorochowik We've prepared final spreadsheet of formats we would like to be included in our utility. Would you like to add and/or remove something?

Also it would be great if you could provide us with some kind of real output from camera in formats listed below - the more diverse formats, the better. We have some testing resources, but they are all generated/converted, so that would be nice to test it with some dumps from real camera.


## RGB-like

| Name    |     VL42 Identifier    |   current support  |   future support   |
|---------|:----------------------:|:------------------:|:------------------:|
| RGB332  | `V4L2_PIX_FMT_RGB332`  | :heavy_check_mark: | :heavy_minus_sign: |
| ARGB444 | `V4L2_PIX_FMT_ARGB444` | :x:                | :heavy_check_mark: |
| RGBA444 | `V4L2_PIX_FMT_RGBA444` | :x:                | :heavy_check_mark: |
| ABGR444 | `V4L2_PIX_FMT_ABGR444` | :x:                | :heavy_check_mark: |
| BGRA444 | `V4L2_PIX_FMT_BGRA444` | :x:                | :heavy_check_mark: |
| ARGB555 | `V4L2_PIX_FMT_ARGB555` | :x:                | :heavy_check_mark: |
| RGBA555 | `V4L2_PIX_FMT_RGBA555` | :x:                | :heavy_check_mark: |
| ABGR555 | `V4L2_PIX_FMT_ABGR555` | :x:                | :heavy_check_mark: |
| BGRA555 | `V4L2_PIX_FMT_BGRA555` | :x:                | :heavy_check_mark: |
| RGB565  | `V4L2_PIX_FMT_RGB565`  | :heavy_check_mark: | :heavy_minus_sign: |
| BGR24   | `V4L2_PIX_FMT_BGR24`   | :heavy_check_mark: | :heavy_minus_sign: |
| RGB24   | `V4L2_PIX_FMT_RGB24`   | :heavy_check_mark: | :heavy_minus_sign: |
| ABGR32  | `V4L2_PIX_FMT_ABGR32`  | :x:                | :heavy_check_mark: |
| BGRA32  | `V4L2_PIX_FMT_BGRA32`  | :heavy_check_mark: | :heavy_minus_sign: |
| RGBA32  | `V4L2_PIX_FMT_RGBA32`  | :heavy_check_mark: | :heavy_minus_sign: |
| ARGB32  | `V4L2_PIX_FMT_ARGB32`  | :x:                | :heavy_check_mark: |

## YUV

| Name |     VL42 Identifier    | Pixel plane |   current support  |   future support   |
|------|:----------------------:|:-----------:|:------------------:|:------------------:|
| UYVY |   `V4L2_PIX_FMT_UYVY`  |    PACKED   | :heavy_check_mark: | :heavy_minus_sign: |
| YUYV |   `V4L2_PIX_FMT_YUYV`  |    PACKED   | :heavy_check_mark: | :heavy_minus_sign: |
| VYUY |   `V4L2_PIX_FMT_VYUY`  |    PACKED   |         :x:        | :heavy_check_mark: |
| YVYU |   `V4L2_PIX_FMT_YVYU`  |    PACKED   |         :x:        | :heavy_check_mark: |
| NV12 |   `V4L2_PIX_FMT_NV12`  | SEMI-PLANAR | :heavy_check_mark: | :heavy_minus_sign: |
| NV21 |   `V4L2_PIX_FMT_NV21`  | SEMI-PLANAR | :heavy_check_mark: | :heavy_minus_sign: |
| I420 |  `V4L2_PIX_FMT_YUV420` |    PLANAR   |         :x:        | :heavy_check_mark: |
| YV12 |  `V4L2_PIX_FMT_YVU420` |    PLANAR   |         :x:        | :heavy_check_mark: |
| I422 | `V4L2_PIX_FMT_YUV422P` |    PLANAR   |         :x:        | :heavy_check_mark: |

## Bayer RGB

| Name |     VL42 Identifier    | current support |   future support   |
|------|:----------------------:|:---------------:|:------------------:|
| RGGB |  `V4L2_PIX_FMT_SRGGB8` |       :x:       | :heavy_check_mark: |
| RG10 | `V4L2_PIX_FMT_SRGGB10` |       :x:       | :heavy_check_mark: |
| RG12 | `V4L2_PIX_FMT_SRGGB12` |       :x:       | :heavy_check_mark: |
| RG16 | `V4L2_PIX_FMT_SRGGB16` |       :x:       | :heavy_check_mark: |

## GREYSCALE

| Name   |   VL42 Identifier   | current support |   future support   |
|--------|:-------------------:|:---------------:|:------------------:|
| GREY   | `V4L2_PIX_FMT_GREY` |       :x:       | :heavy_check_mark: |
| GREY10 |  `V4L2_PIX_FMT_Y10` |       :x:       | :heavy_check_mark: |
| GREY12 |  `V4L2_PIX_FMT_Y12` |       :x:       | :heavy_check_mark: |

**Comment by tgorochowik** [comment]
Looks good it is already quite comprehensive. If more formats are needed in the future we can add them separately (hopefully your code will make it easy to add new formats :wink: )

Please create a new issue with requests for sample images - but please don't wait for us to provide them (I cannot promise any timeline at the moment) - use the generated images for the time being.
