### ISSUE TITLE
Setup github actions

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/raw-image-data-previewer#2]
See: https://docs.github.com/en/actions

Make sure to trigger the CI on push (to master) and on PRs.

As there is no code yet it can run a simple `echo "hello world"` and exit. The goal here is to prepare the infrastructure to run actual tests at a later stage.

**Comment by tgorochowik** [comment]
@MaciejFranikowski 

From now on, please make sure to create PRs before pushing new code to the master branch.

You can push to a different branch here and create a PR from it, or if you prefer you can create a fork and create a PR from your forks.

BTW. the ci configs you pushed to the repository seem to be some samples copied from the internet. This is ok as long as the licence is compatible with the licence used in this project. Is it? In addition you should have mentioned the source of the configuration in your commit.

Things like this (and other things you missed) can be discussed in PRs, that's why it's crucial you use them.

**Comment by blazejulanowicz** [comment]
@tgorochowik

You can be sure that we'll now properly use pushes/PRs.

Regarding CI - this and #3 - we've added two workflows, one as a hello-world-workflow, that starts only on PR/push to master and one linting workflow that starts on push to every branch ([source](https://github.com/actions/starter-workflows) - MIT license). 

Is this correct approach? I mean, should we restrict linting only to master and development branch or leave it as it its?

**Comment by tgorochowik** [comment]
@blazejulanowicz you can indeed mix MIT license with Apache (which we use here), but you have to keep the original license and copyright notice for the imported files.

This is important, please don't ignore licenses in the future. This is especially important when you start working on the code.

I have removed your commits from master and pushed them to a branch here: https://github.com/antmicro-labs/raw-image-data-previewer/tree/ci-copy

It is okay to create a PR based on that (retaining the license information).

But this is really simple stuff, it would be much better if you just wrote this yourself based on the documentation and just push that with the proper license from the start.

**Comment by blazejulanowicz** [comment]
@tgorochowik

Thanks for help. From now on we will be more strict when it comes to licenses.

I am going to remove both workflows and create them again - without using any templates.
