### ISSUE TITLE
Add python linter/formatter checks

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/raw-image-data-previewer#3]
The group chose python to implement the application.

That means we need to check the python code for potential issues each time something is added to the repository.

The goal of this task is to add automatic code checking. Consider using `yapf` or `flake8`.

For example you could run:
```
python3 -m yapf -p -i <list of python files>
test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
```
in the CI.

This depends on #2.

**Comment by MaciejFranikowski** [comment]
Added Python linter, we used the provided yapf code. 
Thanks.
