### ISSUE TITLE
Github Projects

### ISSUE THREAD

**Issue by blazejulanowicz** [antmicro-labs/raw-image-data-previewer#5]
We would like to create Github Projects board to organize tasks and then convert them to issues (for example kanban with extra columns).
Is it acceptable?
[during the meeting I said "Github Pages" - I don't even know why, but I actually meant Github Projects - sorry :( ]

**Comment by tgorochowik** [comment]
Sure, if you wish to use a project, please use: https://github.com/orgs/antmicro-labs/projects/1

**Comment by tgorochowik** [comment]
I created a few issues to highlight what's important to do at the very beginning from our perspective.

Please feel free to create and handle issues for the remaining stuff we discussed during the meeting.

**Comment by blazejulanowicz** [comment]
Okay, we will start working right away.
Thanks!
